# This configuration file defines metadata and settings for the ansible-tunner project.
[project]
name = "ansible-tunner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
